products/urls.py
from django.conf.urls import patterns, url
from .views import ProductsListView, ProductsAddView

urlpatterns = patterns('',
    url(r'^products/$', ProductsListView.as_view(), name='products-list'),
    url(r'^products/add/$', ProductsAddView.as_view(), name='products-add'),
)

products/models.py
from django.db import models
from customers.models import Relation
from jsonfield import JSONField

from common.utils import SingletonModel

# Magento-related models ==============================================================================
class AttributeSet(models.Model):
    name = models.CharField(max_length=300)
    set_id = models.CharField(max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    #attribute = models.ForeignKey(ProductAttribute)
    #attribute_members = models.ManyToManyField(ProductAttribute)

    def __str__(self):
        return self.name


class ProductAttribute(models.Model):
    code = models.CharField(max_length=100)
    attribute_id = models.CharField(max_length=10, blank=True, null=True)
    required = models.BooleanField(blank=True)
    scope = models.CharField(max_length=20, blank=True, null=True)
    attribute_type = models.CharField(max_length=20, blank=True, null=True)
    attribute_set = models.ForeignKey(AttributeSet)
    magento_attribute_set_id = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.code


class Store(models.Model):
    name = models.CharField(max_length=300)
    code = models.CharField(max_length=100)
    is_active = models.BooleanField()
    group_id = models.CharField(max_length=100)
    sort_order = models.CharField(max_length=100)
    store_id = models.CharField(max_length=100)
    website_id = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name


class ProductDeliveryTime(models.Model):
    days = models.PositiveIntegerField()
    verbose_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.verbose_name


class Product(models.Model):
    SIMPLE = 'simple'
    CONFIGURABLE = 'configurable'
    GROUPED = 'grouped'
    BUNDLE = 'bundle'
    VIRTUAL = 'virtual'
    DOWNLOADABLE = 'downloadable'
    PRODUCT_TYPES = (
                        (SIMPLE, 'Simple'),
                        (CONFIGURABLE, 'Configurable'),
                        (GROUPED, 'Grouped'),
                        (BUNDLE, 'Bundle'),
                        (VIRTUAL, 'Virtual'),
                        (DOWNLOADABLE, 'Downloadable'),
                    )

    attribute_set = models.ForeignKey(AttributeSet, blank=True, null=True)
    product_type = models.CharField(max_length=30, choices=PRODUCT_TYPES, default=CONFIGURABLE)
    stock = models.PositiveIntegerField(blank=True, null=True)
    supplier = models.ForeignKey(Relation, limit_choices_to={'is_supplier': True}, blank=True, null=True)
    minimum_order_quantity = models.PositiveIntegerField(blank=True, null=True)
    delivery_time = models.ForeignKey(ProductDeliveryTime, null=True, blank=True)
    sku = models.CharField('SKU', max_length=120, null=True, blank=True)
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    products_associated_with = models.ManyToManyField('self', blank=True)
    magento_product_id = models.CharField(max_length=100, blank=True, null=True)


    def __str__(self):
        return self.name


class ProductOnlineProperties(models.Model):
    store = models.ForeignKey(Store)
    product = models.ForeignKey(Product)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    available_on_website = models.BooleanField(default=False)
    purchable_from_website = models.BooleanField(default=False)
    name = models.CharField(max_length=120, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    advantage_1 = models.CharField(max_length=120, null=True, blank=True)
    advantage_2 = models.CharField(max_length=120, null=True, blank=True)
    advantage_3 = models.CharField(max_length=120, null=True, blank=True)
    #Category???

    class Meta:
        verbose_name_plural = 'Product online properties'
        unique_together = (("store", "product"),)

    def __str__(self):
        return self.name


class DefaultOnlineProperties(models.Model):
    product = models.ForeignKey(Product)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    available_on_website = models.BooleanField(default=False)
    purchable_from_website = models.BooleanField(default=False)
    name = models.CharField(max_length=120, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    advantage_1 = models.CharField(max_length=120, null=True, blank=True)
    advantage_2 = models.CharField(max_length=120, null=True, blank=True)
    advantage_3 = models.CharField(max_length=120, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Default product online properties'

    def __str__(self):
        return self.name


class CategoryTree(SingletonModel):
    category_tree = JSONField()
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)


    #associated_with = models.ForeignKey('self', null=True, blank=True)

    #supplier_sku = models.CharField(max_length=120,null=True, blank=True)
    #order_per_X = models.CharField(max_length=10,null=True, blank=True )
    ##supplier_delivery_time= models.CharField(max_length=10,default=7 )
    
    #Meubis_be_Nederlands= models.BooleanField(default=False)
    #Meubis_be_France= models.BooleanField(default=False)
    #Meubis_nl_Nederlads= models.BooleanField(default=False)
    #Horeca= models.BooleanField(default=False)
    #Color= models.CharField(max_length=120,null=True, blank=True )
    #height=models.CharField(max_length=120,null=True, blank=True )
    #width=models.CharField(max_length=120,null=True, blank=True )
    #lenght=models.CharField(max_length=120,null=True, blank=True )
    #weight= models.PositiveIntegerField(blank=True, null=True)

    #size=models.CharField(max_length=120,null=True, blank=True )
    #advantage_1= models.CharField(max_length=120,null=True, blank=True )
    #advantage_2= models.CharField(max_length=120,null=True, blank=True )
    #advantage_3= models.CharField(max_length=120,null=True, blank=True)


    #name = models.CharField(max_length=120)
    #shortdescription = models.TextField(null=True, blank=True)
    #description = models.TextField(null=True, blank=True)
    #price = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    #sale_price = models.DecimalField(decimal_places=2, max_digits=100,
    #                                 null=True, blank=True)
    #slug = models.SlugField(unique=True)

    #active = models.BooleanField(default=True)


# class ProductAssociation(models.Model):
#     product = models.ForeignKey(Product)
#     target_product = models.ForeignKey(Product, related_name='target_product_set')
#     created_at = models.DateTimeField(auto_now_add=True)

#     class Meta:
#         unique_together = (("product", "target_product"),)



    





# =====================================================================================================


# class Catalog(models.Model):
#     name = models.CharField(max_length=255)
#     slug = models.SlugField(max_length=150)
#     description = models.TextField()
#     created_date = models.DateTimeField(auto_now_add=False, auto_now=True)


# class CatalogCategory(models.Model):
#     catalog = models.ForeignKey('Catalog',
#                                 related_name='categories')
#     parent = models.ForeignKey('self', blank=True, null=True,
#                                related_name='children')
#     name = models.CharField(max_length=300)
#     slug = models.SlugField(max_length=150)
#     description = models.TextField(blank=True)


# class Product(models.Model):
#     category = models.ForeignKey('CatalogCategory',
#                                  related_name='products')
#     PRODUCT_CHOICES = (
#         ('simple', 'Simple'),
#         ('configurable', 'Configurable'),
#         ('grouped', 'Grouped'),
#         ('bundle', 'Bundle'),
#     )

#     DEV_CHOICES = (
#         ('3day', 'Three Days'),
#         ('7days', 'Seven Days'),
#         ('14days', 'Fourteen Days'),
#         ('21 Days', 'Twenty One Days'),
#     )

#     GROUP_CHOICES = (
#         ('Default', 'Default'),
#         ('Beds', 'Beds'),

#     )
#     type_product = models.CharField('Product type', max_length=50,
#                                     choices=PRODUCT_CHOICES, default='simple')
#     delivery = models.CharField('Delivery time', max_length=50,
#                                     choices=DEV_CHOICES, default='Please select')
#     groups = models.CharField('Websites', max_length=50,
#                                     choices=GROUP_CHOICES , default='Please select')

#     weight= models.CharField(max_length=10, default=5)
#     stock = models.CharField(max_length=10,null=True, blank=True)
#     supplier= models.CharField(max_length=120,null=True, blank=True)
#     supplier_sku = models.CharField(max_length=120,null=True, blank=True)
#     order_per_X = models.CharField(max_length=10,null=True, blank=True )
#     supplier_delivery_time= models.CharField(max_length=10,default=7 )
#     Meubis_be_Nederlands= models.BooleanField(default=False)

products/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from meubisapp.views import LoginRequired


class ProductsListView(LoginRequired, TemplateView):
    template_name = "products_list.html"  


class ProductsAddView(LoginRequired, TemplateView):
    template_name = "products_add.html"  

templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" ng-app="meubisApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Meubis Connect{% endblock title %}</title>
    
    <meta name='description' content="{% block meta-description %}{% endblock %}"/>

    {% block css %}
        <!-- Foundation -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/foundation.min.css"/>
        <link rel="stylesheet" href="{% static 'css/meubis.css' %}"/>

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
        {% block extra-css %}
        {% endblock extra-css %}
    {% endblock css %}
  </head>

<body>
    {% block super-content %}
        {% include "navbar.html" %}
        <div class="row">
            <div class="small-6 large-centered columns">
                <alert ng-repeat="alert in alerts" type="alert.type" close="closeAlert($index)" ng-cloak class="text-center alert-show-hide">[[alert.msg]]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</alert>
            </div>
        </div>
        <div class="{%block page-class%}{%endblock page-class%}" {%block controller%}{%endblock controller%}>
        {% block main_body %}
        {% endblock main_body %}
        </div>
    {% endblock super-content %}
    
    {% block footer %}
    {% endblock footer %}

    {% block js %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/foundation.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-resource.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.13/angular-ui-router.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-sanitize.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-animate.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-cookies.js"></script> 

        <script src="{% static 'js/vendor/angular-file-upload.min.js' %}"></script>
        <script src="{% static 'js/vendor/angular-relative-date.js' %}"></script>
        <script src="{% static 'js/vendor/ng-infinite-scroll.min.js' %}"></script>
        <script src="{% static 'js/vendor/mm-foundation-tpls-0.6.0.min.js' %}"></script>
        <script src="{% static 'js/vendor/capitalize.min.js' %}"></script>
        
        <script src="{% static 'js/meubis.js' %}"></script>
        <script src="{% static 'js/ng/ng-meubis.js' %}"></script>
        <script type="text/javascript">
        // Inject constants from django
          angular.module('meubisApp').constant("djangoConstants", {
            user: { id: '{{user.id}}',
                    email: '{{user.email}}',
                    first_name: '{{user.first_name}}',
                    last_name: '{{user.last_name}}',
                    username: '{{user.username}}',
                    phone_number: '{{user.userprofile.phone_number}}',
                    last_login: '{{user.last_login}}',
                    date_joined: '{{user.date_joined}}',
                    is_superuser: '{{user.is_superuser}}',
                    is_active: '{{user.is_active}}',
                    is_admin: '{{user.is_admin}}',
                    is_staff: '{{user.is_staff}}'
                  }
          });
        </script>
        {% block extra-js %}
        {% endblock extra-js %}
    {% endblock js %}
</body>
</html>

templates/common.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html_attr %}{% endblock %}>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrfmiddlewaretoken" content="{{ csrf_token }}">
    {% block meta %}{% endblock %}
    <title>{% block title %}meubis{% endblock %}</title>
	<link href="{% static 'css/foundation.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'angular/angular.min.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr.js' %}"></script>
	<script src="{% static 'js/vendor/jquery.js' %}"></script>
	<script src="{% static 'js/scripts.js' %}"></script>
    
	<script>var scope = {};</script>
    {% block head_js %}{% endblock %}
  </head>
  <body {% block body_attr %}{% endblock %}>
    
    {% block js %}{% endblock %}
	{% block content %}
  {% block before_container %}{% endblock %}
  <div class="container">
    {% block content_layout %}{% endblock %}
  </div>
{% endblock %}
   
    <script src="{% static 'js/foundation.min.js' %}"></script>
	<script>
      $(document).foundation();
    </script>

  </body>
</html>

templates/common_.html
{% extends 'common.html' %}


{% block content %}
  {% block before_container %}{% endblock %}
  <div class="container">
    {% block content_layout %}{% endblock %}
  </div>
{% endblock %}

templates/menu.html
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="{% url 'dashboard' %}">Dashboard</a></h1>
    </li>
	 <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	 </ul>
	<section class="top-bar-section">
   
    <ul class="right">
      <li class="active"><a href="#">store sync</a></li>
	  <li class="active"><a href="#">Account</a></li>
      </ul>
	  
	  <ul class="left">
      
	  <li class="has-dropdown">
	  <a href="#">Manage Customers</a>
	  <ul class="dropdown">
	  <li><a href="#">View/Edit Customers</a> </li>
	  <li><a href="#">Add Customes</a> </li>
	  </ul>
	  
	  <!--<li class="has-dropdown">
	  <a href="#">Categories</a>
	  <ul class="dropdown">
	  <li><a href="#">Manage Categories</a> </li>
	  <li><a href="#">Attributes</a> </li>
	  <li><a href="#">Attributes set</a> </li>
	  </ul>
	  </li> -->
	  
	   <li><a href="products/new/"> Add Products quick link</a></li>
	   <li class="has-dropdown">
	   <a href="#">Manage Products</a>
	   <ul class="dropdown">
	   <li><a href="#">Pending Products </a></li>
	   <li><a href="#">Products </a></li>
	  <li><a href="#">View/Edit Products </a></li>
	   
	   </ul>
	   
	   </li>
    </ul>
  </section>
     
    
</nav>

templates/navbar.html
{% load i18n %}

<div class="contain-to-grid fixed">
  <nav class="top-bar" data-topbar role="navigation">

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <!--li class="has-dropdown">
          <a href="#">{% trans 'Account' %}</a>
          <ul class="dropdown">
            <li><a href="{% url 'logout' %}">{% trans 'Sign out' %}</a></li>
          </ul>
        </li-->
        <li class="divider"></li>
        <li><a href="{% url 'account' %}"><i class="fa fa-user">&nbsp;</i>{% trans 'Account' %}</a></li>
        <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out">&nbsp;</i>{% trans 'Sign out' %}</a></li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-home">&nbsp;</i>{% trans 'Dashboard' %}</a></li>
        <li class="divider"></li>
        <ul class="title-area">
          <li class="name" style="width:8rem;">
          </li>
        </ul>
        <li class="has-dropdown">
          <a href="#">{% trans 'Orders' %}</a>
          <ul class="dropdown">
            <li><a href="{% url 'logout' %}">{% trans 'Item 1' noop %}</a></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">{% trans 'Purchases' %}</a>
          <ul class="dropdown">
            <li><a href="{% url 'logout' %}">{% trans 'Item 1' noop %}</a></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">{% trans 'Relations' %}</a>
          <ul class="dropdown">
            <li><a href="{% url 'relations-list' %}">{% trans 'List' %}</a></li>
            <li><a href="{% url 'relations-add' %}">{% trans 'Add' %}</a></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">{% trans 'Products' %}</a>
          <ul class="dropdown">
            <li><a href="{% url 'products-list' %}">{% trans 'List' %}</a></li>
            <li><a href="{% url 'products-add' %}">{% trans 'Add' %}</a></li>
          </ul>
        </li>
      </ul>
    </section>
  </nav>
</div>

templates/product_edit.html
{% extends 'common.html' %}





{% block before_container %}
  {% include 'menu.html' %}
{% endblock %}

{% block content_layout %}
  <form role="form" method="post">
    <div class="row" style="padding-top:40px;">
      <div class="col-md-5">
        <p class="lead">Product</p>
      </div>
      <div class="col-md-7">
        <button class="btn btn-default">Close</button>
        <button class="btn btn-default btn-danger" type="submit">Save</button>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
      </div>
        <div class="col-md-6">
          <div class="panel panel-info">
            <div class="panel-heading">
              Create new product:
            </div>
            <div class="panel-body">
              {% csrf_token %}
              {{ form|bootstrap }}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </form>
{% endblock %}

templates/product_form.html
{% extends 'common.html' %}
{% load static %}


{% block head_js %}
    <script src="{% static "lodash/lodash.min.js" %}"></script>
    <script src="{% static "controller.js" %}"></script>
    <script>
     scope['get_categories'] = "api_get_categories";
     scope['get_attribute_sets'] = "api_get_attribute_sets";
     scope['get_product_types'] = "api_get_product_types";
     scope['create_product'] = "api_create_product";
    </script>
{% endblock %}

{% block body_attr %}ng-app="meubis" ng-controller="ProductController"{% endblock %}

{% block css %}<style>body { min-height: 2000px; padding-top: 70px; }</style>{% endblock %}

{% block before_container %}
    {% include 'menu.html' %}
{% endblock %}

{% block content_layout %}
   <div class="row">
      <div class="large-12 columns">
      	<div class="panel">  
<form action="{{ action }}" method="POST">
{% csrf_token %}
<p class="lead">Add Product</p>
<div class="row">
 
 <div class='top' id='top'>
 
  <p><label for="id_type_product">Product type:</label> <select id="id_type_product" name="type_product">
<option value="simple" selected="selected">Simple</option>
<option value="configurable">Configurable</option>
<option value="grouped">Grouped</option>
<option value="bundle">Bundle</option>
</select></p>

<label for="id_groups">Groups:</label>
<select id="id_groups" name="groups" onchange="show()">

<option value="Default">Default</option>
<option value="Beds">Beds</option>
</select>
<script>
 function show()
{
jQuery('#top').hide();
jQuery( "#content" ).show();
}
 </script>
</div>

<div id="content" style="display: none">
<div class="row">
<div class="large-4 medium-4 small-4 columns">
<p><label for="id_weight">Weight:</label> <input id="id_weight" maxlength="10" name="weight" type="text" value="5" /></p>
<p><label for="id_stock">Stock:</label> <input id="id_stock" maxlength="10" name="stock" type="text" /></p>
<p><label for="id_delivery">Delivery time:</label> <select id="id_delivery" name="delivery">
<option value="3day">Three Days</option>
<option value="7days">Seven Days</option>
<option value="14days">Fourteen Days</option>
<option value="21 Days">Twenty One Days</option>
</select></p>

</div>

<div class="large-4 medium-4 columns">
<div id='Default' style="display:none">
<p><label for="id_lenght">Lenght:</label> <input id="id_lenght" maxlength="120" name="lenght" type="text" /></p>
<p><label for="id_size">Size:</label> <input id="id_size" maxlength="120" name="size" type="text" /></p>

</div>

<div id="beds" style="display:none">
<p><label for="id_Color">Color:</label> <input id="id_Color" name="Color" maxlength="120" type="text" /></p>
<p><label for="id_width">Width:</label> <input id="id_width" maxlength="120" name="width" type="text" /></p>

<p><label for="id_width">height:</label> <input id="id_width" maxlength="120" name="height" type="text" /></p>

<p><label for="id_lenght">Lenght:</label> <input id="id_lenght" maxlength="120" name="lenght" type="text" /></p>

</div>
</div>

<div class="large-4 medium-4 columns">
<p><label for="id_supplier">Supplier:</label> <input id="id_supplier" maxlength="120" name="supplier" type="text" /></p>
<p><label for="id_supplier_sku">Supplier sku:</label> <input id="id_supplier_sku" maxlength="120" name="supplier_sku" type="text" /></p>
<p><label for="id_order_per_X">Order per X:</label> <input id="id_order_per_X" maxlength="10" name="order_per_X" type="text" /></p>
<p><label for="id_supplier_delivery_time">Supplier delivery time:</label> <input id="id_supplier_delivery_time" maxlength="10" name="supplier_delivery_time" type="text" value="7" /></p>

</div>

</div>


<p><label for="id_category">Category:</label> <select id="id_category" name="category">
<option value="" selected="selected">---------</option>
<option value="1">CatalogCategory object</option>
<option value="2">CatalogCategory object</option>
</select></p>
<p><label for="id_name">Name:</label> <input id="id_name" maxlength="120" name="name" type="text" /></p>

<p><label for="id_shortdescription">Shortdescription:</label> <textarea cols="40" id="id_shortdescription" name="shortdescription" rows="10">
</textarea></p>
<p><label for="id_description">Description:</label> <textarea cols="40" id="id_description" name="description" rows="10">
</textarea></p>
<p><label for="id_price">Price:</label> <input id="id_price" name="price" step="0.01" type="number" value="0.0" /></p>

<p><label for="id_sale_price">Sale price:</label> <input id="id_sale_price" name="sale_price" step="0.01" type="number" /></p>

<p><label for="id_advantage_1">Advantage 1:</label> <input id="id_advantage_1" maxlength="120" name="advantage_1" type="text" /></p>
<p><label for="id_advantage_2">Advantage 2:</label> <input id="id_advantage_2" maxlength="120" name="advantage_2" type="text" /></p>
<p><label for="id_advantage_3">Advantage 3:</label> <input id="id_advantage_3" maxlength="120" name="advantage_3" type="text" /></p>

<div class="row">
<div class="large-6 medium-6 columns">
<p>Websites </p>
<label for="id_Meubis_be_Nederlands">Nederlands:</label> <input id="id_Meubis_be_Nederlands" name="Meubis_be_Nederlands" type="checkbox" />
<label for="id_Meubis_be_France">France:</label> <input id="id_Meubis_be_France" name="Meubis_be_France" type="checkbox" />
<label for="id_Meubis_nl_Nederlads">Meubis.nl :</label> <input id="id_Meubis_nl_Nederlads" name="Meubis_nl_Nederlads" type="checkbox" />
<label for="id_Horeca">Horeca:</label> <input id="id_Horeca" name="Horeca" type="checkbox" />
 </div>
 </div>
 
 
 <div id="configarable" style="display:none">
 <p> Select associated Products </p>
 <div id="ascociate">
 </div>
 </div>
 
 <div id="related" style="display:none">
 <p> Select Related Products</p>
 <div id="dvLoading"></div>
 </div>
 <label for="images">Images:</label>
 <input type="file" name=""> <div id="add">&#43;</div>
 
<input class="small button" type="submit" value="continue" />
 </div>
</div>
 
 
 
 
 
 
 
 </form> 
</div>
</div>
</div>
	
	
	
{% endblock %}

templates/product_image.html
{% extends 'common.html' %}
{% load static %}


{% block head_js %}
    <script src="{% static "lodash/lodash.min.js" %}"></script>
    <script src="{% static "controller.js" %}"></script>
    <script>
     scope['get_categories'] = "api_get_categories";
     scope['get_attribute_sets'] = "api_get_attribute_sets";
     scope['get_product_types'] = "api_get_product_types";
     scope['create_product'] = "api_create_product";
    </script>
{% endblock %}

{% block body_attr %}ng-app="meubis" ng-controller="ProductController"{% endblock %}

{% block css %}<style>body { min-height: 2000px; padding-top: 70px; }</style>{% endblock %}

{% block before_container %}
    {% include 'menu.html' %}
{% endblock %}

{% block content_layout %}
   <div class="row">
      <div class="large-12 columns">
      	<div class="panel">  
<h1> Related Products </h1>
<div id='related'>  </div>
<h2> Associated Products </h1>
<div id='associated'>  </div>
		
<form action="{{ action }}" method="POST">
{% csrf_token %}
<p class="lead">Add Product Image</p>
<div class="row">
 <div class="large-8 medium-8 columns">
 {{ form.as_p }}
<input class="small button" type="submit" value="continue" />
 
</div>
 </div>
 {% endblock %}

templates/test.html
test 2